<MyLayout>
    BoxLayout:
        orientation: "vertical"
        size: root.width, root.height

        Carousel:
            direction: 'right'

            Image:
                source: 'image/safira_sleeping.jpg'
            AsyncImage:
                source:

            Image:
                source: 'image/safira_sleeping2.jpg'

            Image:
                source: 'image/safira_sleeping3.jpg'
