<MyLayout>
    canvas.before:
        Color:
            rgba: (0,0,1,1)
        Rectangle:
            pos: self.pos
            size: self.size

    BoxLayout:
        orientation: "vertical"
        size: root.width, root.height
        padding: 50
        spacing: 20

        Button:
            text: "Hello World"
            background_color: (1,0,0,1)

        Button:
            text: "Goodbye World"
            background_color: (1,0,0,1)